Add rarity level to ChefSingle view + images for the rarity
cryptoChefs/app pull request #161
Opened 2022-03-22 14:34 UTC by natayra

2022-03-22 22:23 UTC, rolandsaven requested changes
Hey, just before I deep dive into the code and start to recommend some solutions (as dependency on the order of an array is not the best tactic) I wonder if this is a final solution? I had a look at the images and I'm right that only the background is being changed right? 

Do you think we're planning to introduce all the images, if yes, we're talking about 100x images in which case I'd start thinking of the best solution here.

2022-03-22 22:23 UTC, rolandsaven commented on src/views/ChefSingle/ChefSingle.jsx
> +  const classicImages = [
Would you mind defining these, outside of the component? These are mostly static and don't need to be executed again on re-render

2022-03-23 09:31 UTC, natayra commented
> Hey, just before I deep dive into the code and start to recommend some solutions (as dependency on the order of an array is not the best tactic) I wonder if this is a final solution? I had a look at the images and I'm right that only the background is being changed right?
> 
> Do you think we're planning to introduce all the images, if yes, we're talking about 100x images in which case I'd start thinking of the best solution here.

Hi. The images are only different in background and border color, yes. There are 6 images for each rarity level (classic, epic and legendary) making a total of 18. When you mention 100x images are you talking in total on the app? 
Please let me know if there is a better solution. I thought using the svgs already with the right background, border and size would be less code to define all of that.

I agree using the order to set this is not the best solution but I still also looking for how can I do it better. Any suggestion appreciated

2022-03-23 20:16 UTC, rolandsaven approved these changes

2022-03-23 20:20 UTC, merged